version: '3.8'

services:
  #database
  postrges:
    image:  postgres:16-alpine
    container_name: notery_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres_password_british123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #cache
  redis:
    image: redis:7-alpine
    container_name: notery_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:

